require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # v3.5: Eager load for faster responses (production-like)
  config.eager_load = true

  # Show full error reports.
  config.consider_all_requests_local = true

  # v3.5: Disable server timing (overhead)
  config.server_timing = false

  # v3.5: Enable caching
  config.action_controller.perform_caching = true
  config.public_file_server.headers = { "cache-control" => "public, max-age=#{1.hour.to_i}" }

  # Use memory store for fast caching
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: ENV.fetch("APP_HOST", "localhost"), port: 3000 }
  config.action_controller.default_url_options = { host: ENV.fetch("APP_HOST", "localhost"), port: 3000 }
  Rails.application.routes.default_url_options = { host: ENV.fetch("APP_HOST", "localhost"), port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # v3.5: Disable verbose query logs (performance)
  config.active_record.verbose_query_logs = false

  # v3.5: Disable query log tags (performance)
  config.active_record.query_log_tags_enabled = false

  # v3.5: Disable verbose job logs (performance)
  config.active_job.verbose_enqueue_logs = false

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # v3.5: Disable view annotation (performance)
  config.action_view.annotate_rendered_view_with_filenames = false

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
